"""Add last_read_at to customers table

Revision ID: 2a54796cbf2e
Revises: 658b9447be77
Create Date: 2025-06-13 20:23:13.570794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a54796cbf2e'
down_revision: Union[str, None] = '658b9447be77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('last_read_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.create_index(op.f('ix_customers_business_id'), 'customers', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_business_id'), table_name='customers')
    op.drop_column('customers', 'last_read_at')
    # ### end Alembic commands ###