"""add_targeted_event_table_and_update_relations

Revision ID: 412246714b94
Revises: 21e7c88e7ecd
Create Date: 2025-05-31 22:30:26.950254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412246714b94'
down_revision: Union[str, None] = '21e7c88e7ecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###