"""Add pending_approval and rejected message statuses

Revision ID: 784712d8523d
Revises: 8860831c4bf3
Create Date: 2025-06-16 13:38:42.659708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784712d8523d'
down_revision: Union[str, None] = '8860831c4bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###