"""Add autopilot fields to business profile

Revision ID: 8860831c4bf3
Revises: 2a54796cbf2e
Create Date: 2025-06-14 09:50:01.933319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8860831c4bf3'
down_revision: Union[str, None] = '2a54796cbf2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###