"""initial_dev_schema

Revision ID: b24e17e3e73f
Revises: 
Create Date: 2025-05-26 18:40:27.342020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b24e17e3e73f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('business_goal', sa.String(), nullable=True),
    sa.Column('primary_services', sa.String(), nullable=True),
    sa.Column('representative_name', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('twilio_number', sa.String(), nullable=True),
    sa.Column('twilio_sid', sa.String(), nullable=True),
    sa.Column('messaging_service_sid', sa.String(), nullable=True),
    sa.Column('business_phone_number', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notify_owner_on_reply_with_link', sa.Boolean(), nullable=False),
    sa.Column('enable_ai_faq_auto_reply', sa.Boolean(), nullable=False),
    sa.Column('structured_faq_data', sa.JSON(), nullable=True),
    sa.Column('default_appointment_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('availability_style', sa.String(), nullable=True),
    sa.Column('smart_hours_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('manual_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_business_profiles_business_name'), 'business_profiles', ['business_name'], unique=True)
    op.create_index(op.f('ix_business_profiles_id'), 'business_profiles', ['id'], unique=False)
    op.create_table('appointment_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appt_avail_business_day_active', 'appointment_availability', ['business_id', 'day_of_week', 'is_active'], unique=False)
    op.create_index(op.f('ix_appointment_availability_business_id'), 'appointment_availability', ['business_id'], unique=False)
    op.create_index(op.f('ix_appointment_availability_id'), 'appointment_availability', ['id'], unique=False)
    op.create_table('business_owner_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('context_type', sa.String(), nullable=True),
    sa.Column('key_phrases', sa.JSON(), nullable=True),
    sa.Column('style_notes', sa.JSON(), nullable=True),
    sa.Column('personality_traits', sa.JSON(), nullable=True),
    sa.Column('message_patterns', sa.JSON(), nullable=True),
    sa.Column('special_elements', sa.JSON(), nullable=True),
    sa.Column('last_analyzed', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('lifecycle_stage', sa.String(), nullable=True),
    sa.Column('pain_points', sa.Text(), nullable=True),
    sa.Column('interaction_history', sa.Text(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('opted_in', sa.Boolean(), nullable=True),
    sa.Column('sms_opt_in_status', sa.Enum('pending', 'opted_in', 'opted_out', 'not_set', 'pending_confirmation', name='opt_in_status_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_generating_roadmap', sa.Boolean(), nullable=True),
    sa.Column('last_generation_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone', 'business_id', name='uq_customer_phone_per_business')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_tag_name_per_business')
    )
    op.create_index(op.f('ix_tags_business_id'), 'tags', ['business_id'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_table('consent_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('message_sid', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'opted_in', 'opted_out', 'not_set', 'pending_confirmation', name='consent_log_status_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consent_log_customer_business_status', 'consent_log', ['customer_id', 'business_id', 'status'], unique=False)
    op.create_index(op.f('ix_consent_log_id'), 'consent_log', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_customer_business', 'conversations', ['customer_id', 'business_id'], unique=False)
    op.create_index('idx_conversation_status', 'conversations', ['status'], unique=False)
    op.create_table('customer_tags',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'tag_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('inbound', 'outbound', 'scheduled_message', 'draft', 'ai_draft', 'outbound_ai_reply', 'system', 'appointment_proposal', 'appointment_confirmation', 'appointment_reschedule_suggestion', 'appointment_cancellation_notice', 'appointment_reminder', 'appointment_thank_you', name='message_type_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('pending_review', 'pending', 'pending_send', 'scheduled', 'queued', 'sent', 'delivered', 'failed', 'received', 'deleted', 'auto_replied_faq', 'approved', 'rejected_draft', 'manually_sent', 'draft', name='message_status_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('sender_type', sa.Enum('business', 'customer', 'system', name='message_sender_type_enum', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_send_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('twilio_message_sid', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_business', 'messages', ['business_id'], unique=False)
    op.create_index('idx_message_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_message_customer', 'messages', ['customer_id'], unique=False)
    op.create_index('idx_message_scheduled_send_at', 'messages', ['scheduled_send_at'], unique=False)
    op.create_index('idx_message_sender_type', 'messages', ['sender_type'], unique=False)
    op.create_index('idx_message_source', 'messages', ['source'], unique=False)
    op.create_index('idx_message_status', 'messages', ['status'], unique=False)
    op.create_index('idx_message_type', 'messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_message_type'), 'messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_messages_sender_type'), 'messages', ['sender_type'], unique=False)
    op.create_index(op.f('ix_messages_source'), 'messages', ['source'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('ix_messages_twilio_message_sid'), 'messages', ['twilio_message_sid'], unique=False)
    op.create_table('appointment_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_initiated_message_id', sa.Integer(), nullable=True),
    sa.Column('business_proposal_message_id', sa.Integer(), nullable=True),
    sa.Column('customer_reply_to_proposal_message_id', sa.Integer(), nullable=True),
    sa.Column('original_message_text', sa.Text(), nullable=True),
    sa.Column('parsed_requested_time_text', sa.String(), nullable=True),
    sa.Column('parsed_requested_datetime_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending_owner_action', 'business_initiated_pending_customer_reply', 'customer_confirmed_pending_owner_approval', 'customer_requested_reschedule', 'customer_declined_proposal', 'confirmed_by_owner', 'owner_proposed_reschedule', 'declined_by_owner', 'cancelled_by_owner', 'completed', 'no_show', 'cancelled_by_customer', name='appointment_request_status_enum_v2', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('resolution_type', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('customer_initiated', 'business_initiated', name='appointment_request_source_enum_v2', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('ai_suggested_reply', sa.Text(), nullable=True),
    sa.Column('confirmed_datetime_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_suggested_time_text', sa.String(), nullable=True),
    sa.Column('owner_suggested_datetime_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_reschedule_suggestion', sa.Text(), nullable=True),
    sa.Column('owner_actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_removed_reason', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_proposal_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_initiated_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_reply_to_proposal_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appt_req_business_customer_status', 'appointment_requests', ['business_id', 'customer_id', 'status'], unique=False)
    op.create_index('idx_appt_req_confirmed_time', 'appointment_requests', ['confirmed_datetime_utc'], unique=False)
    op.create_index(op.f('ix_appointment_requests_business_id'), 'appointment_requests', ['business_id'], unique=False)
    op.create_index(op.f('ix_appointment_requests_business_proposal_message_id'), 'appointment_requests', ['business_proposal_message_id'], unique=False)
    op.create_index(op.f('ix_appointment_requests_confirmed_datetime_utc'), 'appointment_requests', ['confirmed_datetime_utc'], unique=False)
    op.create_index(op.f('ix_appointment_requests_customer_id'), 'appointment_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_appointment_requests_customer_initiated_message_id'), 'appointment_requests', ['customer_initiated_message_id'], unique=False)
    op.create_index(op.f('ix_appointment_requests_customer_reply_to_proposal_message_id'), 'appointment_requests', ['customer_reply_to_proposal_message_id'], unique=False)
    op.create_index(op.f('ix_appointment_requests_id'), 'appointment_requests', ['id'], unique=False)
    op.create_index(op.f('ix_appointment_requests_resolution_type'), 'appointment_requests', ['resolution_type'], unique=False)
    op.create_index(op.f('ix_appointment_requests_source'), 'appointment_requests', ['source'], unique=False)
    op.create_index(op.f('ix_appointment_requests_status'), 'appointment_requests', ['status'], unique=False)
    op.create_table('engagements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending_review', 'pending', 'pending_send', 'scheduled', 'queued', 'sent', 'delivered', 'failed', 'received', 'deleted', 'auto_replied_faq', 'approved', 'rejected_draft', 'manually_sent', 'draft', name='engagement_status_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('parent_engagement_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_engagement_id'], ['engagements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_engagement_customer_business', 'engagements', ['customer_id', 'business_id'], unique=False)
    op.create_index('idx_engagement_is_hidden', 'engagements', ['is_hidden'], unique=False)
    op.create_index('idx_engagement_source', 'engagements', ['source'], unique=False)
    op.create_index('idx_engagement_status', 'engagements', ['status'], unique=False)
    op.create_index(op.f('ix_engagements_id'), 'engagements', ['id'], unique=False)
    op.create_index(op.f('ix_engagements_source'), 'engagements', ['source'], unique=False)
    op.create_table('roadmap_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('smsContent', sa.Text(), nullable=False),
    sa.Column('smsTiming', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending_review', 'pending', 'pending_send', 'scheduled', 'queued', 'sent', 'delivered', 'failed', 'received', 'deleted', 'auto_replied_faq', 'approved', 'rejected_draft', 'manually_sent', 'draft', name='roadmap_message_status_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('send_datetime_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('relevance', sa.Text(), nullable=True),
    sa.Column('success_indicator', sa.Text(), nullable=True),
    sa.Column('no_response_plan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_roadmap_customer_business', 'roadmap_messages', ['customer_id', 'business_id'], unique=False)
    op.create_index('idx_roadmap_status', 'roadmap_messages', ['status'], unique=False)
    op.create_index(op.f('ix_roadmap_messages_id'), 'roadmap_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_messages_id'), table_name='roadmap_messages')
    op.drop_index('idx_roadmap_status', table_name='roadmap_messages')
    op.drop_index('idx_roadmap_customer_business', table_name='roadmap_messages')
    op.drop_table('roadmap_messages')
    op.drop_index(op.f('ix_engagements_source'), table_name='engagements')
    op.drop_index(op.f('ix_engagements_id'), table_name='engagements')
    op.drop_index('idx_engagement_status', table_name='engagements')
    op.drop_index('idx_engagement_source', table_name='engagements')
    op.drop_index('idx_engagement_is_hidden', table_name='engagements')
    op.drop_index('idx_engagement_customer_business', table_name='engagements')
    op.drop_table('engagements')
    op.drop_index(op.f('ix_appointment_requests_status'), table_name='appointment_requests')
    op.drop_index(op.f('ix_appointment_requests_source'), table_name='appointment_requests')
    op.drop_index(op.f('ix_appointment_requests_resolution_type'), table_name='appointment_requests')
    op.drop_index(op.f('ix_appointment_requests_id'), table_name='appointment_requests')
    op.drop_index(op.f('ix_appointment_requests_customer_reply_to_proposal_message_id'), table_name='appointment_requests')
    op.drop_index(op.f('ix_appointment_requests_customer_initiated_message_id'), table_name='appointment_requests')
    op.drop_index(op.f('ix_appointment_requests_customer_id'), table_name='appointment_requests')
    op.drop_index(op.f('ix_appointment_requests_confirmed_datetime_utc'), table_name='appointment_requests')
    op.drop_index(op.f('ix_appointment_requests_business_proposal_message_id'), table_name='appointment_requests')
    op.drop_index(op.f('ix_appointment_requests_business_id'), table_name='appointment_requests')
    op.drop_index('idx_appt_req_confirmed_time', table_name='appointment_requests')
    op.drop_index('idx_appt_req_business_customer_status', table_name='appointment_requests')
    op.drop_table('appointment_requests')
    op.drop_index(op.f('ix_messages_twilio_message_sid'), table_name='messages')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_source'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index('idx_message_type', table_name='messages')
    op.drop_index('idx_message_status', table_name='messages')
    op.drop_index('idx_message_source', table_name='messages')
    op.drop_index('idx_message_sender_type', table_name='messages')
    op.drop_index('idx_message_scheduled_send_at', table_name='messages')
    op.drop_index('idx_message_customer', table_name='messages')
    op.drop_index('idx_message_conversation', table_name='messages')
    op.drop_index('idx_message_business', table_name='messages')
    op.drop_table('messages')
    op.drop_table('customer_tags')
    op.drop_index('idx_conversation_status', table_name='conversations')
    op.drop_index('idx_conversation_customer_business', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_consent_log_id'), table_name='consent_log')
    op.drop_index('idx_consent_log_customer_business_status', table_name='consent_log')
    op.drop_table('consent_log')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_business_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('business_owner_styles')
    op.drop_index(op.f('ix_appointment_availability_id'), table_name='appointment_availability')
    op.drop_index(op.f('ix_appointment_availability_business_id'), table_name='appointment_availability')
    op.drop_index('idx_appt_avail_business_day_active', table_name='appointment_availability')
    op.drop_table('appointment_availability')
    op.drop_index(op.f('ix_business_profiles_id'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_business_name'), table_name='business_profiles')
    op.drop_table('business_profiles')
    # ### end Alembic commands ###
