"""detect_initial_prod_schema_deviations

Revision ID: f37fc31d5934
Revises: 
Create Date: 2025-05-26 14:50:52.610238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f37fc31d5934'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_sms_id'), table_name='scheduled_sms')
    op.drop_table('scheduled_sms')
    op.drop_index(op.f('idx_appt_avail_business_day'), table_name='appointment_availability')
    op.create_index('idx_appt_avail_business_day_active', 'appointment_availability', ['business_id', 'day_of_week', 'is_active'], unique=False)
    op.alter_column('appointment_requests', 'status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('pending_owner_action', 'business_initiated_pending_customer_reply', 'customer_confirmed_pending_owner_approval', 'customer_requested_reschedule', 'customer_declined_proposal', 'confirmed_by_owner', 'owner_proposed_reschedule', 'declined_by_owner', 'cancelled_by_owner', 'completed', 'no_show', 'cancelled_by_customer', name='appointment_request_status_enum_v2', native_enum=False, create_constraint=True),
               existing_nullable=False)
    op.alter_column('appointment_requests', 'source',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('customer_initiated', 'business_initiated', name='appointment_request_source_enum_v2', native_enum=False, create_constraint=True),
               existing_nullable=False)
    op.drop_index(op.f('idx_appt_req_customer_reply_msg_id'), table_name='appointment_requests')
    op.drop_index(op.f('idx_appt_req_resolution_type'), table_name='appointment_requests')
    op.drop_index(op.f('idx_appt_req_source'), table_name='appointment_requests')
    op.create_index(op.f('ix_appointment_requests_customer_reply_to_proposal_message_id'), 'appointment_requests', ['customer_reply_to_proposal_message_id'], unique=False)
    op.alter_column('business_owner_styles', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('business_owner_styles', 'key_phrases',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('business_owner_styles', 'style_notes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('business_owner_styles', 'personality_traits',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('business_owner_styles', 'message_patterns',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('business_owner_styles', 'special_elements',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_business_owner_styles_context_type'), table_name='business_owner_styles')
    op.drop_index(op.f('idx_business_owner_styles_last_analyzed'), table_name='business_owner_styles')
    op.drop_index(op.f('ix_business_owner_styles_id'), table_name='business_owner_styles')
    op.create_unique_constraint(None, 'business_owner_styles', ['business_id'])
    op.drop_constraint(op.f('business_owner_styles_business_id_fkey'), 'business_owner_styles', type_='foreignkey')
    op.create_foreign_key(None, 'business_owner_styles', 'business_profiles', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('business_profiles', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('business_profiles', 'messaging_service_sid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('business_profiles', 'notify_owner_on_reply_with_link',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='If true, send SMS to owner (on business_phone_number) upon customer reply, including a deep link to the conversation.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('business_profiles', 'enable_ai_faq_auto_reply',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='If true, AI will attempt to auto-reply to common questions using data from structured_faq_data.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('business_profiles', 'structured_faq_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='JSONB store for business hours, address, website, and custom Q&A pairs for AI auto-reply function.',
               existing_nullable=True)
    op.drop_index(op.f('idx_business_phone_number'), table_name='business_profiles')
    op.alter_column('consent_log', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('consent_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('consent_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('idx_consent_customer_replied'), table_name='consent_log')
    op.create_index('idx_consent_log_customer_business_status', 'consent_log', ['customer_id', 'business_id', 'status'], unique=False)
    op.drop_constraint(op.f('consent_log_customer_id_fkey'), 'consent_log', type_='foreignkey')
    op.drop_constraint(op.f('consent_log_business_id_fkey'), 'consent_log', type_='foreignkey')
    op.create_foreign_key(None, 'consent_log', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'consent_log', 'business_profiles', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('conversations', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('conversations', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('conversations', 'last_message_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('idx_conversation_business'), table_name='conversations')
    op.drop_index(op.f('idx_conversation_customer'), table_name='conversations')
    op.create_index('idx_conversation_customer_business', 'conversations', ['customer_id', 'business_id'], unique=False)
    op.drop_constraint(op.f('conversations_business_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_constraint(op.f('conversations_customer_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversations', 'business_profiles', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_customertag_customer'), table_name='customer_tags')
    op.drop_index(op.f('idx_customertag_tag'), table_name='customer_tags')
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customers', 'sms_opt_in_status',
               existing_type=postgresql.ENUM('pending', 'pending_confirmation', 'opted_in', 'opted_out', 'not_set', name='opt_in_status_enum'),
               type_=sa.Enum('pending', 'opted_in', 'opted_out', 'not_set', 'pending_confirmation', name='opt_in_status_enum', native_enum=False, create_constraint=True),
               nullable=False)
    op.alter_column('customers', 'last_generation_attempt',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_customers_customer_name'), table_name='customers')
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_unique_constraint('uq_customer_phone_per_business', 'customers', ['phone', 'business_id'])
    op.drop_constraint(op.f('customers_business_id_fkey'), 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'business_profiles', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('engagements', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('engagements', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('engagements', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('engagements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('engagements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('engagements', 'message_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_engagements_business'), table_name='engagements')
    op.create_index('idx_engagement_customer_business', 'engagements', ['customer_id', 'business_id'], unique=False)
    op.create_index('idx_engagement_status', 'engagements', ['status'], unique=False)
    op.create_index(op.f('ix_engagements_source'), 'engagements', ['source'], unique=False)
    op.drop_constraint(op.f('engagements_parent_engagement_id_fkey'), 'engagements', type_='foreignkey')
    op.drop_constraint(op.f('engagements_customer_id_fkey'), 'engagements', type_='foreignkey')
    op.drop_constraint(op.f('engagements_message_id_fkey'), 'engagements', type_='foreignkey')
    op.drop_constraint(op.f('engagements_business_id_fkey'), 'engagements', type_='foreignkey')
    op.create_foreign_key(None, 'engagements', 'business_profiles', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'engagements', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'engagements', 'engagements', ['parent_engagement_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'engagements', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('messages', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'sender_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('business', 'customer', 'system', name='message_sender_type_enum', native_enum=False, create_constraint=True),
               nullable=True,
               existing_server_default=sa.text("'business'::character varying"))
    op.alter_column('messages', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('messages', 'message_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('idx_message_scheduled_send_at', 'messages', ['scheduled_send_at'], unique=False)
    op.create_index(op.f('ix_messages_message_type'), 'messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_messages_sender_type'), 'messages', ['sender_type'], unique=False)
    op.create_index(op.f('ix_messages_source'), 'messages', ['source'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('ix_messages_twilio_message_sid'), 'messages', ['twilio_message_sid'], unique=False)
    op.drop_constraint(op.f('messages_customer_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_business_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_parent_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'messages', ['parent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'business_profiles', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_column('messages', 'scheduled_time')
    op.alter_column('roadmap_messages', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('roadmap_messages', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('roadmap_messages', 'smsContent',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('roadmap_messages', 'smsTiming',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('roadmap_messages', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('roadmap_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('roadmap_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_roadmap_message'), table_name='roadmap_messages')
    op.create_index('idx_roadmap_customer_business', 'roadmap_messages', ['customer_id', 'business_id'], unique=False)
    op.create_index('idx_roadmap_status', 'roadmap_messages', ['status'], unique=False)
    op.drop_constraint(op.f('roadmap_messages_message_id_fkey'), 'roadmap_messages', type_='foreignkey')
    op.drop_constraint(op.f('roadmap_messages_customer_id_fkey'), 'roadmap_messages', type_='foreignkey')
    op.drop_constraint(op.f('roadmap_messages_business_id_fkey'), 'roadmap_messages', type_='foreignkey')
    op.create_foreign_key(None, 'roadmap_messages', 'business_profiles', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'roadmap_messages', 'messages', ['message_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'roadmap_messages', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_tag_business_id'), table_name='tags')
    op.drop_index(op.f('idx_tag_business_name'), table_name='tags')
    op.drop_index(op.f('idx_tag_name'), table_name='tags')
    op.create_index(op.f('ix_tags_business_id'), 'tags', ['business_id'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_business_id'), table_name='tags')
    op.create_index(op.f('idx_tag_name'), 'tags', ['name'], unique=False)
    op.create_index(op.f('idx_tag_business_name'), 'tags', ['business_id', 'name'], unique=False)
    op.create_index(op.f('idx_tag_business_id'), 'tags', ['business_id'], unique=False)
    op.drop_constraint(None, 'roadmap_messages', type_='foreignkey')
    op.drop_constraint(None, 'roadmap_messages', type_='foreignkey')
    op.drop_constraint(None, 'roadmap_messages', type_='foreignkey')
    op.create_foreign_key(op.f('roadmap_messages_business_id_fkey'), 'roadmap_messages', 'business_profiles', ['business_id'], ['id'])
    op.create_foreign_key(op.f('roadmap_messages_customer_id_fkey'), 'roadmap_messages', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(op.f('roadmap_messages_message_id_fkey'), 'roadmap_messages', 'messages', ['message_id'], ['id'])
    op.drop_index('idx_roadmap_status', table_name='roadmap_messages')
    op.drop_index('idx_roadmap_customer_business', table_name='roadmap_messages')
    op.create_index(op.f('idx_roadmap_message'), 'roadmap_messages', ['message_id'], unique=False)
    op.alter_column('roadmap_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('roadmap_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('roadmap_messages', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('roadmap_messages', 'smsTiming',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('roadmap_messages', 'smsContent',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('roadmap_messages', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('roadmap_messages', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('messages', sa.Column('scheduled_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(op.f('messages_parent_id_fkey'), 'messages', 'messages', ['parent_id'], ['id'])
    op.create_foreign_key(op.f('messages_business_id_fkey'), 'messages', 'business_profiles', ['business_id'], ['id'])
    op.create_foreign_key(op.f('messages_customer_id_fkey'), 'messages', 'customers', ['customer_id'], ['id'])
    op.drop_index(op.f('ix_messages_twilio_message_sid'), table_name='messages')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_source'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_type'), table_name='messages')
    op.drop_index('idx_message_scheduled_send_at', table_name='messages')
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('messages', 'message_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('messages', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('messages', 'sender_type',
               existing_type=sa.Enum('business', 'customer', 'system', name='message_sender_type_enum', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'business'::character varying"))
    op.alter_column('messages', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'engagements', type_='foreignkey')
    op.drop_constraint(None, 'engagements', type_='foreignkey')
    op.drop_constraint(None, 'engagements', type_='foreignkey')
    op.drop_constraint(None, 'engagements', type_='foreignkey')
    op.create_foreign_key(op.f('engagements_business_id_fkey'), 'engagements', 'business_profiles', ['business_id'], ['id'])
    op.create_foreign_key(op.f('engagements_message_id_fkey'), 'engagements', 'messages', ['message_id'], ['id'])
    op.create_foreign_key(op.f('engagements_customer_id_fkey'), 'engagements', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(op.f('engagements_parent_engagement_id_fkey'), 'engagements', 'engagements', ['parent_engagement_id'], ['id'])
    op.drop_index(op.f('ix_engagements_source'), table_name='engagements')
    op.drop_index('idx_engagement_status', table_name='engagements')
    op.drop_index('idx_engagement_customer_business', table_name='engagements')
    op.create_index(op.f('idx_engagements_business'), 'engagements', ['business_id'], unique=False)
    op.alter_column('engagements', 'message_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('engagements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('engagements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('engagements', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('engagements', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('engagements', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key(op.f('customers_business_id_fkey'), 'customers', 'business_profiles', ['business_id'], ['id'])
    op.drop_constraint('uq_customer_phone_per_business', 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.create_index(op.f('ix_customers_customer_name'), 'customers', ['customer_name'], unique=False)
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('customers', 'last_generation_attempt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('customers', 'sms_opt_in_status',
               existing_type=sa.Enum('pending', 'opted_in', 'opted_out', 'not_set', 'pending_confirmation', name='opt_in_status_enum', native_enum=False, create_constraint=True),
               type_=postgresql.ENUM('pending', 'pending_confirmation', 'opted_in', 'opted_out', 'not_set', name='opt_in_status_enum'),
               nullable=True)
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('idx_customertag_tag'), 'customer_tags', ['tag_id'], unique=False)
    op.create_index(op.f('idx_customertag_customer'), 'customer_tags', ['customer_id'], unique=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_customer_id_fkey'), 'conversations', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(op.f('conversations_business_id_fkey'), 'conversations', 'business_profiles', ['business_id'], ['id'])
    op.drop_index('idx_conversation_customer_business', table_name='conversations')
    op.create_index(op.f('idx_conversation_customer'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('idx_conversation_business'), 'conversations', ['business_id'], unique=False)
    op.alter_column('conversations', 'last_message_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('conversations', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('conversations', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'consent_log', type_='foreignkey')
    op.drop_constraint(None, 'consent_log', type_='foreignkey')
    op.create_foreign_key(op.f('consent_log_business_id_fkey'), 'consent_log', 'business_profiles', ['business_id'], ['id'])
    op.create_foreign_key(op.f('consent_log_customer_id_fkey'), 'consent_log', 'customers', ['customer_id'], ['id'])
    op.drop_index('idx_consent_log_customer_business_status', table_name='consent_log')
    op.create_index(op.f('idx_consent_customer_replied'), 'consent_log', ['customer_id', 'replied_at'], unique=False)
    op.alter_column('consent_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('consent_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('consent_log', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('idx_business_phone_number'), 'business_profiles', ['business_phone_number'], unique=False)
    op.alter_column('business_profiles', 'structured_faq_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSONB store for business hours, address, website, and custom Q&A pairs for AI auto-reply function.',
               existing_nullable=True)
    op.alter_column('business_profiles', 'enable_ai_faq_auto_reply',
               existing_type=sa.BOOLEAN(),
               comment='If true, AI will attempt to auto-reply to common questions using data from structured_faq_data.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('business_profiles', 'notify_owner_on_reply_with_link',
               existing_type=sa.BOOLEAN(),
               comment='If true, send SMS to owner (on business_phone_number) upon customer reply, including a deep link to the conversation.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('business_profiles', 'messaging_service_sid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('business_profiles', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.drop_constraint(None, 'business_owner_styles', type_='foreignkey')
    op.create_foreign_key(op.f('business_owner_styles_business_id_fkey'), 'business_owner_styles', 'business_profiles', ['business_id'], ['id'])
    op.drop_constraint(None, 'business_owner_styles', type_='unique')
    op.create_index(op.f('ix_business_owner_styles_id'), 'business_owner_styles', ['id'], unique=False)
    op.create_index(op.f('idx_business_owner_styles_last_analyzed'), 'business_owner_styles', ['last_analyzed'], unique=False)
    op.create_index(op.f('idx_business_owner_styles_context_type'), 'business_owner_styles', ['context_type'], unique=False)
    op.alter_column('business_owner_styles', 'special_elements',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('business_owner_styles', 'message_patterns',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('business_owner_styles', 'personality_traits',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('business_owner_styles', 'style_notes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('business_owner_styles', 'key_phrases',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('business_owner_styles', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_appointment_requests_customer_reply_to_proposal_message_id'), table_name='appointment_requests')
    op.create_index(op.f('idx_appt_req_source'), 'appointment_requests', ['source'], unique=False)
    op.create_index(op.f('idx_appt_req_resolution_type'), 'appointment_requests', ['resolution_type'], unique=False)
    op.create_index(op.f('idx_appt_req_customer_reply_msg_id'), 'appointment_requests', ['customer_reply_to_proposal_message_id'], unique=False)
    op.alter_column('appointment_requests', 'source',
               existing_type=sa.Enum('customer_initiated', 'business_initiated', name='appointment_request_source_enum_v2', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('appointment_requests', 'status',
               existing_type=sa.Enum('pending_owner_action', 'business_initiated_pending_customer_reply', 'customer_confirmed_pending_owner_approval', 'customer_requested_reschedule', 'customer_declined_proposal', 'confirmed_by_owner', 'owner_proposed_reschedule', 'declined_by_owner', 'cancelled_by_owner', 'completed', 'no_show', 'cancelled_by_customer', name='appointment_request_status_enum_v2', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index('idx_appt_avail_business_day_active', table_name='appointment_availability')
    op.create_index(op.f('idx_appt_avail_business_day'), 'appointment_availability', ['business_id', 'day_of_week'], unique=False)
    op.create_table('scheduled_sms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('send_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('roadmap_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_hidden', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], name=op.f('scheduled_sms_business_id_fkey')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('scheduled_sms_customer_id_fkey')),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap_messages.id'], name=op.f('scheduled_sms_roadmap_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('scheduled_sms_pkey'))
    )
    op.create_index(op.f('ix_scheduled_sms_id'), 'scheduled_sms', ['id'], unique=False)
    # ### end Alembic commands ###
